// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var codeish, inc_score, increment, index, level, load_file, score, terminal;
    increment = 5;
    codeish = '';
    index = 0;
    score = -1;
    terminal = $('.console');
    level = {
      0: 'code.c',
      1: 'code.cpp',
      2: 'code.py',
      3: 'code.rb',
      4: 'code.lua',
      5: 'code.go'
    };
    inc_score = function() {
      score += 1;
      return $(".score").html(score);
    };
    load_file = function(filename) {
      return $.ajax({
        url: "code_samples/" + filename,
        success: function(data) {
          return codeish = data;
        }
      });
    };
    inc_score();
    load_file(level[score]);
    return $(document).keyup(function(event) {
      terminal.append(codeish.slice(index, index + increment));
      terminal.scrollTop(terminal[0].scrollHeight);
      index += increment;
      if (index > codeish.length) {
        inc_score();
        index = 0;
        load_file(level[score]);
        return terminal.html("");
      }
    });
  });

}).call(this);
